"""add appointment reason and time to session

Revision ID: 7a747524d68e
Revises: 84a9e29ff3f9
Create Date: 2026-09-20 02:36:18.809641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a747524d68e'
down_revision: Union[str, Sequence[str], None] = '84a9e29ff3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('appointment_reason_text', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('appointment_when_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'appointment_when_text')
    op.drop_column('sessions', 'appointment_reason_text')
    # ### end Alembic commands ###
