"""add consent tracking and access audit log

Revision ID: 84a9e29ff3f9
Revises: 568e155bf6cb
Create Date: 2026-09-20 02:35:38.502539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a9e29ff3f9'
down_revision: Union[str, Sequence[str], None] = '568e155bf6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_log_session_id'), 'access_log', ['session_id'], unique=False)
    op.add_column('sessions', sa.Column('consent_given_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'consent_given_at')
    op.drop_index(op.f('ix_access_log_session_id'), table_name='access_log')
    op.drop_table('access_log')
    # ### end Alembic commands ###
